
///////////////////////////////////////////////////////////////////////
//
//                               ATTENTION!!!
//
//   Don't edit this file directly.
//   It's entirely generated by slides-list.js script.
//   All changes will be overwritten.
//
///////////////////////////////////////////////////////////////////////

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SlidesListingComponent } from './node_modules/slides-finder/src/app/slides/slides-listing/slides-listing.component';
import { SlidesRenderComponent } from '../render/node_modules/slides-render-angular/src/app/slides/slides-render/slides-render.component';



export const SlidesList = [
SlidesListingComponent,
SlidesRenderComponent,

];
export const SlidesListMap = [
{path: 'mockups', component: SlidesListingComponent},
{path: 'mockups/CMEBOCIEEO', component: SlidesRenderComponent}
];
