
///////////////////////////////////////////////////////////////////////
//
//                               ATTENTION!!!
//
//   Generated by slides-generator for Angular.
//   Don't edit this file - all changes will be overwritten.
//
///////////////////////////////////////////////////////////////////////

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SlidesListingComponent } from './node_modules/slides-render-angular/src/app/slides/slides-listing/slides-listing.component';


import { CMEBOCIEEO } from '../render/mockups/CMEBOCIEEO/component';

export const SlidesList = [
SlidesListingComponent,
CMEBOCIEEO
];
export const SlidesListMap = [
{path: 'mockups', component: SlidesListingComponent},
{path: 'mockups/CMEBOCIEEO', component: CMEBOCIEEO}
];
